events {}

http {
  include /etc/nginx/mime.types;

  map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
  }

  server {
    listen __DASHBOARD_PORT__;

    location /zimamod-api/ {
      client_max_body_size 64k;
      proxy_pass http://127.0.0.1:__API_PORT__/;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /zimamod-runtime/ {
      alias /runtime/;
      add_header Cache-Control "no-store";
    }

    location /mod/ {
      alias /mods/;
      add_header Cache-Control "no-store";
    }

    location /store/ {
      proxy_pass http://127.0.0.1:__API_PORT__/store-assets/;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location = /v2/settings/fe.custom {
      proxy_pass http://127.0.0.1:80;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Host $http_host;
      proxy_set_header X-Forwarded-Port $server_port;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header Accept-Encoding "";
      proxy_intercept_errors on;
      error_page 400 =200 @empty_fe_custom;
    }

    location @empty_fe_custom {
      default_type application/json;
      return 200 '{"data":{}}';
    }

    location / {
      client_max_body_size 0;
      proxy_pass http://127.0.0.1:80;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Host $http_host;
      proxy_set_header X-Forwarded-Port $server_port;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
      proxy_set_header Accept-Encoding "";

      sub_filter_once on;
      sub_filter '</body>' '<script src="/zimamod-runtime/loader.js?v=1.1.37"></script></body>';
    }
  }
}
