"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");

const root = path.resolve(__dirname, "..");

function read(relativePath) {
  return fs.readFileSync(path.join(root, relativePath), "utf8");
}

test("ZimaOS import metadata uses literal default ports", () => {
  for (const composeFile of ["docker-compose.yml", "docker-compose.build.yml"]) {
    const compose = read(composeFile);
    assert.doesNotMatch(compose, /\$\{ZIMAMOD_(?:DASHBOARD|API)_PORT/);
    assert.match(compose, /ZIMAMOD_DASHBOARD_PORT: "8088"/);
    assert.match(compose, /ZIMAMOD_API_PORT: "8090"/);
    assert.match(compose, /HOST_PROC_DIR: \/host\/proc/);
    assert.match(compose, /HOST_SYS_DIR: \/host\/sys/);
    assert.match(compose, /source: \/proc\s+target: \/host\/proc\s+read_only: true/);
    assert.match(compose, /source: \/sys\s+target: \/host\/sys\s+read_only: true/);
    assert.match(compose, /port_map: "8088"/);
  }
});

test("API startup refreshes the catalog without installing bundled mods", () => {
  const entrypoint = read("api/entrypoint.sh");
  assert.match(entrypoint, /\/data\/store\/\$mod_id/);
  assert.doesNotMatch(entrypoint, /\/data\/mod\/\$mod_id/);
  assert.doesNotMatch(entrypoint, /bundled-mods-seeded|Initially installed bundled mod/);
});

test("Weather Widget includes its supported themes", () => {
  const mod = read("mods/weather-widget/mod.js");
  const manifest = JSON.parse(read("mods/weather-widget/zimamod.json"));
  const liquidTheme = read("mods/weather-widget/themes/liquid-glass.css");
  const sandedTheme = read("mods/weather-widget/themes/sanded-glass.css");

  assert.match(mod, /label: "CasaOS"/);
  assert.match(mod, /label: "Aero"/);
  assert.match(mod, /label: "Liquid Glass"/);
  assert.match(mod, /label: "Sanded Glass"/);
  assert.match(mod, /themes\/sanded-glass\.css/);
  assert.doesNotMatch(mod, /Pure Liquid Glass|pure-liquid-glass/);
  assert.match(mod, /-theme-row/);
  assert.match(mod, /-theme-switch/);
  assert.match(mod, /grid-template-columns:\s*repeat\(auto-fit, minmax\(92px, 1fr\)\)/);
  assert.doesNotMatch(mod, /backdrop-filter:\s*blur/);
  assert.doesNotMatch(liquidTheme, /backdrop-filter:\s*blur/);
  assert.match(mod, /feDisplacementMap/);
  assert.match(mod, /feTurbulence/);
  assert.match(liquidTheme, /filter:\s*url\("#zimamod-weather-liquid-distortion"\)/);
  assert.match(sandedTheme, /zimamod-weather-theme-sanded/);
  assert.match(sandedTheme, /filter:\s*url\("#zimamod-weather-liquid-distortion"\)/);
  assert.doesNotMatch(sandedTheme, /theme-brushed|brushed-distortion/);
  assert.match(mod, /mutationTouchesWeather/);
  assert.match(mod, /beginStartupMount/);
  assert.match(mod, /startupObserver\?\.disconnect/);
  assert.doesNotMatch(mod, /setInterval\(enforceSingleWidget/);
  assert.match(mod, /nativeCount >= 2 \|\| hasWidgetTitle\(element, "widget settings"\)/);
  assert.equal(manifest.version, "1.3.9");
});

test("Widget Sortable tolerates hidden native widgets", () => {
  const mod = read("mods/widget-sortable-zimaos/mod.js");
  const docs = read("mods/widget-sortable-zimaos/README.md");

  assert.match(mod, /hasDashboardWidgets/);
  assert.match(mod, /nativeCount >= 2 \|\| hasWidgetTitle\(element, "widget settings"\)/);
  assert.match(mod, /shouldWaitForMissing/);
  assert.match(mod, /!\["clock", "system", "storage", "network", "widget-settings"\]\.includes\(id\)/);
  assert.match(mod, /missingIds = order\.filter\(id => !byId\.has\(id\) && shouldWaitForMissing\(id\)\)/);
  assert.match(docs, /Widget Settings/i);
});

test("Dashboard Themes ships as an independent theme manager", () => {
  const mod = read("mods/dashboard-themes/mod.js");
  const css = read("mods/dashboard-themes/mod.css");
  const sanded = read("mods/dashboard-themes/themes/sanded-glass.css");
  const liquid = read("mods/dashboard-themes/themes/liquid-glass.css");
  const aero = read("mods/dashboard-themes/themes/aero.css");
  const casaos = read("mods/dashboard-themes/themes/casaos.css");
  const chaos = read("mods/dashboard-themes/themes/chaos.css");
  const manifest = JSON.parse(read("mods/dashboard-themes/zimamod.json"));
  const store = read("runtime/store.js");

  assert.equal(manifest.name, "Dashboard Themes");
  assert.equal(manifest.category, "Visual Effects");
  assert.deepEqual(manifest.scripts, ["mod.js"]);
  assert.deepEqual(manifest.styles, ["mod.css"]);
  assert.match(mod, /const ASSET_MOD_ID = "dashboard-themes"/);
  assert.match(mod, /window\.ZimaMOD\.assetUrl\(ASSET_MOD_ID, relativePath\)/);
  assert.doesNotMatch(mod, /window\.ZimaMOD\.assetUrl\(MOD_ID, relativePath\)/);
  assert.match(mod, /const FILTER_ID = MOD_ID \+ "-distortion"/);
  assert.match(mod, /"sanded-glass"/);
  assert.match(mod, /"liquid-glass"/);
  assert.match(mod, /aero:/);
  assert.match(mod, /casaos:/);
  assert.match(mod, /chaos:/);
  assert.match(mod, /themes\/sanded-glass\.css/);
  assert.match(mod, /themes\/liquid-glass\.css/);
  assert.match(mod, /themes\/aero\.css/);
  assert.match(mod, /themes\/casaos\.css/);
  assert.match(mod, /themes\/chaos\.css/);
  assert.match(mod, /loadThemeCss/);
  assert.match(mod, /loadShadowThemeCss/);
  assert.match(mod, /window\.ZimaMODDashboardThemes/);
  assert.match(mod, /openSettings/);
  assert.match(mod, /window\.ZimaMOD\.setConfig\(CONFIG_ID/);
  assert.match(mod, /setupShadowRoot/);
  assert.match(mod, /overflow:\s*visible !important/);
  assert.match(mod, /\.\$\{APP_CLASS\}\s*\{\s*position:\s*relative !important;\s*overflow:\s*visible !important;/);
  assert.doesNotMatch(mod, /translateZ\(0\)/);
  assert.match(mod, /const APP_BLUR_CLASS = MOD_ID \+ "-app-blur"/);
  assert.match(mod, /element\.classList\.add\(APP_BLUR_CLASS\)/);
  assert.match(mod, /\.apps-panel-app-card-item\[data-app-key\]/);
  assert.match(mod, /function markTopAppSurfaces/);
  assert.match(mod, /function injectTopStyles/);
  assert.match(mod, /> :not\(button\)\s*\{/);
  assert.doesNotMatch(mod, /element\.remove\(\)/);
  assert.match(mod, /\[role="menu"\]/);
  assert.doesNotMatch(mod, /\[role="listbox"\]\s*\{\s*position:\s*relative/);
  assert.match(mod, /\[role="listbox"\]\s*\{\s*z-index:\s*50;/);
  assert.match(mod, /\.blur-background/);
  assert.match(mod, /\.bg-blur/);
  assert.match(mod, /BG_HEX_RE/);
  assert.match(mod, /backdrop-blur-sm/);
  assert.match(mod, /backdrop-saturate-180/);
  assert.match(mod, /closest\("\.zimamod-weather"\)/);
  assert.doesNotMatch(css, /data-zimamod-dashboard-theme=/);
  assert.match(css, /#zimamod-dashboard-themes-modal/);
  assert.match(sanded, /data-zimamod-dashboard-theme="sanded-glass"/);
  assert.match(liquid, /data-zimamod-dashboard-theme="liquid-glass"/);
  assert.match(liquid, /zimamod-dashboard-themes-app-blur/);
  assert.match(liquid, /filter:\s*url\("#zimamod-dashboard-themes-distortion"\)/);
  assert.match(liquid, /--dtm-app-filter:\s*none/);
  assert.match(liquid, /\.zimamod-dashboard-themes-header\s*\{\s*background:\s*transparent !important;/);
  assert.match(aero, /data-zimamod-dashboard-theme="aero"/);
  assert.match(casaos, /data-zimamod-dashboard-theme="casaos"/);
  assert.match(casaos, /var\(--background-2/);
  assert.match(chaos, /data-zimamod-dashboard-theme="chaos"/);
  assert.match(store, /DTM Settings/);
  assert.match(store, /const bind = \(selector, eventName, handler\)/);
  assert.match(store, /ZimaMODDashboardThemes\?\.openSettings/);
});

test("Resource Alerts ships as a built-for-ZimaMOD monitoring widget", () => {
  const mod = read("mods/resource-alerts/mod.js");
  const css = read("mods/resource-alerts/mod.css");
  const docs = read("mods/resource-alerts/README.md");
  const sanded = read("mods/resource-alerts/themes/sanded-glass.css");
  const liquid = read("mods/resource-alerts/themes/liquid-glass.css");
  const aero = read("mods/resource-alerts/themes/aero.css");
  const casaos = read("mods/resource-alerts/themes/casaos.css");
  const chaos = read("mods/resource-alerts/themes/chaos.css");
  const manifest = JSON.parse(read("mods/resource-alerts/zimamod.json"));
  const rootDocs = read("README.md");
  const modDocs = read("mods/README.md");
  const server = read("api/server.js");
  const loader = read("runtime/loader.js");

  assert.equal(manifest.name, "Resource Alerts");
  assert.equal(manifest.category, "System Monitoring");
  assert.deepEqual(manifest.scripts, ["mod.js"]);
  assert.deepEqual(manifest.styles, ["mod.css"]);
  assert.equal(manifest.origin.type, "native");
  assert.match(mod, /const MOD_ID = "resource-alerts"/);
  assert.match(mod, /const THEMES = \{/);
  assert.match(mod, /"sanded-glass"/);
  assert.match(mod, /"liquid-glass"/);
  assert.match(mod, /aero:/);
  assert.match(mod, /casaos:/);
  assert.match(mod, /chaos:/);
  assert.match(mod, /applyTheme/);
  assert.match(mod, /data-config="theme"/);
  assert.match(mod, /updateModalStatus/);
  assert.match(mod, /data-tab="\$\{id\}"/);
  assert.match(mod, /Status/);
  assert.match(mod, /Events/);
  assert.match(mod, /Notes/);
  assert.match(mod, /Settings/);
  assert.match(mod, /eventsDefaultShown/);
  assert.match(mod, /data-config="notes"/);
  assert.match(mod, /notesTabHtml/);
  assert.match(mod, /hostProcMounted/);
  assert.match(mod, /getResourceAlertsState/);
  assert.match(mod, /clearResourceAlertsEvents/);
  assert.match(mod, /if \(!rows\.length\) return config\.checks/);
  assert.match(mod, /configValue\("theme", config\.theme\)/);
  assert.doesNotMatch(mod, />Cancel<\/button>/);
  assert.match(mod, /Top Memory Processes/);
  assert.match(mod, /Host Runtime/);
  assert.match(mod, /ZFS \/ RAID Health/);
  assert.doesNotMatch(mod, /Future ideas/);
  assert.doesNotMatch(mod, /renderWidget\(lastSnapshot\);\s*renderModalBody\(\);/);
  assert.match(mod, /collectMetrics/);
  assert.match(mod, /window\.ZimaMOD\.getSystemMetrics/);
  assert.match(mod, /\/zimamod-api\/metrics/);
  assert.doesNotMatch(mod, /detectSystemMetrics|percentBeforeLabel|dashboardText/);
  assert.match(mod, /checkService/);
  assert.match(mod, /hasDashboardWidgets/);
  assert.match(mod, /nativeCount >= 2 \|\| hasWidgetTitle\(element, "widget settings"\)/);
  assert.match(mod, /widget\?\.remove\(\)/);
  assert.match(mod, /Notification\.requestPermission/);
  assert.match(mod, /api\.telegram\.org/);
  assert.match(mod, /Gotify/i);
  assert.match(mod, /window\.ZimaMOD\.setConfig\(MOD_ID, config\)/);
  assert.match(mod, /role="dialog"/);
  assert.match(css, /\.zimamod-resource-alerts/);
  assert.match(css, /--zra-frame/);
  assert.match(css, /color:\s*#111827 !important/);
  assert.match(css, /background:\s*#fff !important/);
  assert.match(css, /\.zimamod-resource-alerts-modal input\s*\{[\s\S]*?color:\s*black;/);
  assert.match(css, /\.zimamod-resource-alerts-modal input\s*\{[\s\S]*?padding-left:\s*5px;/);
  assert.match(sanded, /data-zimamod-resource-alerts-theme="sanded-glass"/);
  assert.match(liquid, /data-zimamod-resource-alerts-theme="liquid-glass"/);
  assert.match(aero, /data-zimamod-resource-alerts-theme="aero"/);
  assert.match(casaos, /data-zimamod-resource-alerts-theme="casaos"/);
  assert.match(chaos, /data-zimamod-resource-alerts-theme="chaos"/);
  assert.match(docs, /\/zimamod-api\/metrics/);
  assert.match(docs, /http:\/\/192\.168\.0\.96:8088\/zimamod-api\/health/);
  assert.match(docs, /target: \/host\/proc/);
  assert.match(server, /url\.pathname === "\/metrics"/);
  assert.match(server, /readCpuSample/);
  assert.match(server, /memoryMetrics/);
  assert.match(server, /diskMetrics/);
  assert.match(server, /networkMetrics/);
  assert.match(server, /readNetworkSample/);
  assert.match(server, /systemInfo/);
  assert.match(server, /topMemoryProcesses/);
  assert.match(server, /HOST_PROC_MOUNTED/);
  assert.match(server, /storageHealth/);
  assert.match(server, /evaluateResourceAlerts/);
  assert.match(server, /scheduleResourceAlertsMonitor/);
  assert.match(server, /sendServerTelegram/);
  assert.match(server, /sendServerGotify/);
  assert.match(server, /url\.pathname === "\/resource-alerts"/);
  assert.match(server, /readSensors/);
  assert.match(loader, /getSystemMetrics/);
  assert.match(loader, /getResourceAlertsState/);
  assert.match(loader, /clearResourceAlertsEvents/);
  assert.match(rootDocs, /\| Resource Alerts \| Built for ZimaMOD \|/);
  assert.match(modDocs, /\| Resource Alerts \| Built for ZimaMOD \|/);
});
